import { ChatStats } from '@/services/ChatsServices'

export type DashboardCardData = {
  title: string
  id: string
  total: string
  bottomTitle: string
  bottomSub: string
}

export const createDashboardCardsData = (stats: ChatStats, loading: boolean): DashboardCardData[] => [
  {
    title: "Total Chats",
    id: "1",
    total: loading ? "..." : stats.totalChats.toLocaleString(),
    bottomTitle: "Chat History Count",
    bottomSub: "Overall conversations handled",
  },
  {
    title: "Chat Total Token",
    id: "2",
    total: loading ? "..." : stats.promptTokens.toLocaleString(),
    bottomTitle: "Your Token In Chat",
    bottomSub: "Sum of all chat tokens used",
  },
  {
    title: "Respond Token",
    id: "3",
    total: loading ? "..." : stats.completionTokens.toLocaleString(),
    bottomTitle: "AI Respond Output",
    bottomSub: "Output tokens generated by AI",
  },

  {
    title: "Total Token Used",
    id: "4",
    total: loading ? "..." : stats.totalTokens.toLocaleString(),
    bottomTitle: "Chat and Respond Total Tokens",
    bottomSub: "Combined input and output tokens",
  },

]
